easy_admin:
    site_name: 'Tableau de bord'
    design:
        brand_color: '#1ABC9C'
        menu:
            - { label: 'Accueil', route: 'home', icone: 'home'}
            - { entity: 'User', label: 'Utilisateurs', icon: 'user'}
            - { label: 'Mes BD'}
            - { entity: 'Produit', label: 'Produits', params: {sortDirection: 'ASC'}}
            - { entity: 'Genre', icon: 'tag'}
    entities:
        # List the entity class name you want to manage
#        - App\Entity\Produit
#        - App\Entity\Genre
#        - App\Entity\Editeur
#        - App\Entity\Fournisseur
#        - App\Entity\Auteur
#        - App\Entity\Category
#        - App\Entity\User
        Produit:
            class: App\Entity\Produit
            params: { sortDirection: 'ASC'}
        Genre:
            class: App\Entity\Genre
        User:
            class: App\Entity\User

    user:
        display_name: true
        display_avatar: true
        name_property_path: 'userName'
        avatar_property_path: 'gravatar'    
